version: '3'
networks:
  web:
    external: true
    name: traefik_web  

services:
  feed-tool:
    build: .
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feed-tool.rule=Host(`[your-domain]`)"
      - "traefik.http.routers.feed-tool.entrypoints=web"
      - "traefik.http.services.feed-tool.loadbalancer.server.port=8080"
    networks:
      - web
    restart: always