name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Replace with your default branch if not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy MyFunction \
            --runtime go113 \
            --trigger-http \
            --allow-unauthenticated
